### PR TITLE
sap_hypervisor_node_preconfigure: Minor fixes

### PR DESCRIPTION
**Pull request by newkit**

### CODE REVIEW

**Comment by berndfinger** [comment]
LGTM.
@newkit: What was the reason for the double quotes around `true` in https://github.com/sap-linuxlab/community.sap_install/pull/553/commits/df5b58604a06c83ec48701ded90015d70f5bb7b7 (just for the records)?

**Comment by newkit** [comment]
@berndfinger Simply the fact that the double quotes are needed there in order to work.

**Comment by Wabri** [comment]
@berndfinger it is the definition of a k8s configuration and in this case `feature.node.kubernetes.io/network-sriov.capable` takes a string and not a boolean.

You can find the documentation for this component in here https://docs.openshift.com/container-platform/4.9/networking/hardware_networks/about-sriov.html

And also a configuration example in here https://docs.openshift.com/container-platform/4.8/networking/hardware_networks/configuring-sriov-device.html#nw-sriov-networknodepolicy-object_configuring-sriov-device

**Comment by berndfinger** [comment]
@Wabri Many thanks!

**Pull request merged**
