### PR TITLE
docs(CONTRIBUTORS): update SUSE contributors file

### PR DESCRIPTION
**Pull request by Wabri**

### CODE REVIEW

**Comment by sean-freeman** [comment]
@Wabri Very good spot, this file should be updated. It's right to keep a list of prior contributors from the origin code.

The file actually misses the last 5 names from the list in metadata > https://github.com/sap-linuxlab/community.sap_install/blob/main/galaxy.yml#L19

**Comment by Wabri** [comment]
I think I'm done with it, there are some description that we want to change?

**Review by sean-freeman — APPROVED** [review]
@Wabri probably should update some of the text, but won't block the PR for that reason 👍 lgtm

**Review by marcelmamula — APPROVED** [review]
LGTM

**Pull request merged**
