### PR TITLE
Merge dev to main for release 1.2.3

### PR DESCRIPTION
**Pull request by berndfinger**

### CODE REVIEW

**Review by ja9fuchs — APPROVED** [review]
LGTM

Unrelated to the committed changes:
yamllint complaints in the sap_vm_preconfigure role still to be addressed.

**Review by sean-freeman — APPROVED** [review]
lgtm 👍 

Ignore linting errors on experimental roles stub code

**Comment by berndfinger** [comment]
> LGTM
> 
> Unrelated to the committed changes: yamllint complaints in the sap_vm_preconfigure role still to be addressed.
Thanks. We'll have a look into this for one of the next versions.

**Review by rainerleber — APPROVED** [review]
lgtm

**Pull request merged**
