### PR TITLE
sap_*: add sles python3-rpm install to resolve #649

### LINKED ISSUE #649: sap_*_preconfigure: package_facts
sap_*_preconfigure Ansible Role's may fail upon first usage of Ansible Module `package_facts` when python3-rpm OS Package is not installed for the System Python.

Specifically noted [for SLES in the Ansible Module in-line documentation](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/package_facts.py#L39) but should be considered for RHEL also as an administrator may alter any OS Image.

```yaml
- name: Ensure OS Package for Python Lib of rpm bindings is enabled for System Python - RHEL
  ansible.builtin.command: yum install --assumeyes python3-rpm
  when: ansible_os_family == "RedHat"

- name: Ensure OS Package for Python Lib of rpm bindings is enabled for System Python - SLES
  ansible.builtin.command: zypper install --no-confirm --auto-agree-with-licenses python3-rpm
  when: ansible_os_family == "Suse"

- name: Gather package facts
....
....
```

### PR DESCRIPTION
**Pull request by sean-freeman**
sap_*: add sles python3-rpm install to resolve #649

### CODE REVIEW

**Review by berndfinger — APPROVED** [review]
LGTM

**Review by marcelmamula — CHANGES_REQUESTED** [review]
I think it should be changed to package mode. Zypper in package works by default and it can be installed.

Tested on AWS and IBM Cloud VS
```yaml
    - name: Install python3-rpm
      ansible.builtin.package:
        name: python3-rpm
        state: present
```

**Comment by marcelmamula** [comment]
Test done:
```yaml
    - name: Remove python3-rpm
      ansible.builtin.package:
        name: python3-rpm
        state: absent

    - name: Gather package facts after removal
      ansible.builtin.package_facts:
      ignore_errors: true

    - name: Install python3-rpm
      ansible.builtin.package:
        name: python3-rpm
        state: present

    - name: Gather package facts after install
      ansible.builtin.package_facts:
      ignore_errors: true
```

```console
TASK [Remove python3-rpm] ********************************************************************************************************************************************************************************
changed: [ae1ers]
changed: [ae1ascs]

TASK [Gather package facts after removal] ****************************************************************************************************************************************************************
[WARNING]: Found "rpm" but Failed to import the required Python library (rpm) on ae1ers's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If
the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
fatal: [ae1ers]: FAILED! => {"changed": false, "msg": "Could not detect a supported package manager from the following list: ['pacman', 'apt', 'pkg_info', 'rpm', 'portage', 'pkg', 'apk'], or the required Python library is not installed. Check warnings for details."}
...ignoring
[WARNING]: Found "rpm" but Failed to import the required Python library (rpm) on ae1ascs's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If
the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
fatal: [ae1ascs]: FAILED! => {"changed": false, "msg": "Could not detect a supported package manager from the following list: ['apk', 'rpm', 'apt', 'pacman', 'portage', 'pkg', 'pkg_info'], or the required Python library is not installed. Check warnings for details."}
...ignoring

TASK [Install python3-rpm] *******************************************************************************************************************************************************************************
changed: [ae1ascs]
changed: [ae1ers]

TASK [Gather package facts after install] ****************************************************************************************************************************************************************
ok: [ae1ers]
ok: [ae1ascs]
```

**Comment by sean-freeman** [comment]
Different code used and new PR opened

**Pull request closed without merging**
