### PR TITLE
sap_swpm: Remove pids module

### PR DESCRIPTION
**Pull request by berndfinger**
We should better remove the `community.general.pids` module. Advantages:
- No dependency on `community.general` in the role sap_swpm, simplifying support for downstream versions
- No more Python related package installations at the beginning of the role
- Probably also solving https://github.com/sap-linuxlab/community.sap_install/issues/716.

Solves https://github.com/sap-linuxlab/community.sap_install/issues/719.

### CODE REVIEW

**Review by marcelmamula — COMMENTED** [review]
@berndfinger Tested and it works for sap_swpm, but it breaks recent changes in sap_ha_pacemaker_cluster and ha_cluster roles.

New ASCS/ERS post steps were added that include python3-pip with pexpect for ansible.builtin.expect module in https://github.com/sap-linuxlab/community.sap_install/blob/ef0636394cedc582ce4e4614b22b9da6e207f20f/roles/sap_ha_pacemaker_cluster/tasks/Suse/post_steps_nwas_abap_ascs_ers.yml#L20

@ja9fuchs We would need to take these removed python/pip steps and put them into sap_ha role instead.

**Review by sean-freeman — APPROVED** [review]

**Comment by berndfinger** [comment]
> @berndfinger did you figure out your issues that you mentioned?

None of the issues I had seen were related to this code change but rather to wrong parameter settings.

**Review by marcelmamula — APPROVED** [review]
LGTM

**Comment by berndfinger** [comment]
Aborting PR due to an error when resolving a merge conflict.

**Pull request closed without merging**
