### PR TITLE
sap_*_preconfigure: SLES compatibility

### PR DESCRIPTION
**Pull request by sean-freeman**
sap_*_preconfigure: SLES compatibility

### CODE REVIEW

**Comment by sean-freeman** [comment]
Require permission/approval to merge into main; please base decision on current version control activities.

I have already reviewed and approved the code changes for SLES compatibility, the code itself does not require review.

**Comment by sean-freeman** [comment]
Additional commits (related primarily to linting and FCQN) which have been added to `dev` branch will be merged with this same PR.

**Comment by berndfinger** [comment]
lgtm.

**Review by berndfinger — APPROVED** [review]
lgtm.

**Pull request merged**
