### PR TITLE
fix(sap_ha_pacemaker_cluster): update with new condition

### LINKED ISSUE #615: sap_ha_pacemaker_cluster: sap_ha_pacemaker_cluster_hacluster_user_password ignored
Current workflow is not accepting variable sap_ha_pacemaker_cluster_hacluster_user_password for HA cluster password because:
1. ha_cluster_hacluster_password is always defined in defaults as ""
2. __sap_ha_pacemaker_cluster_hacluster_user_password i always emptied because ha_cluster_hacluster_password  is always defined.
https://github.com/sap-linuxlab/community.sap_install/blob/5ee5cbe030ad152edfe96567155812f9abcdc25f/roles/sap_ha_pacemaker_cluster/tasks/import_hacluster_vars_from_inventory.yml#L68
3. Construct common vars is always skipped because __sap_ha_pacemaker_cluster_hacluster_user_password  is defined in previous step, so sap_ha_pacemaker_cluster_hacluster_user_password  is never used.
https://github.com/sap-linuxlab/community.sap_install/blob/5ee5cbe030ad152edfe96567155812f9abcdc25f/roles/sap_ha_pacemaker_cluster/tasks/construct_vars_common.yml#L21
4. ha_cluster_hacluster_password is "" because __sap_ha_pacemaker_cluster_hacluster_user_password is defined and empty ""
https://github.com/sap-linuxlab/community.sap_install/blob/5ee5cbe030ad152edfe96567155812f9abcdc25f/roles/sap_ha_pacemaker_cluster/tasks/construct_final_hacluster_vars.yml#L74

Solution: Update import_hacluster_vars file with conditional for empty string for ha_cluster_hacluster_password  from defaults.
```
# ha_cluster_hacluster_password
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_repos'"
  when:
    - ha_cluster_hacluster_password is defined
    - ha_cluster_hacluster_password | length > 0
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_hacluster_user_password: "{{ ha_cluster_hacluster_password }}"
  no_log: true  # handle credentials with care
```

### PR DESCRIPTION
**Pull request by Wabri**
Closes #615

### CODE REVIEW

**Review by marcelmamula — APPROVED** [review]
LGTM, thank you for doing it for me as I had too many file change in my VSC.

**Comment by Wabri** [comment]
Yes, my fault. I open a new pr with a revert merge commit.

**Comment by sean-freeman** [comment]
@Wabri @marcelmamula a PR should really not be merged without review from it's origin author / key maintainer or a cross-review from another SLL-OSI Governance Board Member. This particular Ansible Role contains a lot of complex logic for HANA HA, NWAS ABAP HA (ASCS-ERS, PAS-AAS) and NWAS JAVA HA (SCS-ERS) - so I always run an integration test to confirm

At initial inspection this PR is benign, but `ha_cluster_hacluster_password` should not have a default `''`, therefore this PR should be unnecessary. I'll re-test in a few days but I cannot see anything wrong with this PR so no harm, no foul 🙂

**Comment by marcelmamula** [comment]
@sean-freeman I have broke down flow in Issue #615 where you can see how it is getting cleared because of those conditions. Since this role is acting as wrapper around ha_cluster, we need to make sure that input variable for this role does not get emptied and then pass empty password into ha_cluster.

**Comment by marcelmamula** [comment]
This is actual result from step 2 from mentioned issue:
```
TASK [../community.sap_install/roles/sap_ha_pacemaker_cluster : Debug before first change] ***********************************************
ok: [nw750ahahdb0] => (item=ha_cluster_hacluster_password) => {
    "ansible_loop_var": "item",
    "ha_cluster_hacluster_password": "",
    "item": "ha_cluster_hacluster_password"
}
ok: [nw750ahahdb0] => (item=sap_ha_pacemaker_cluster_hacluster_user_password) => {
    "ansible_loop_var": "item",
    "item": "sap_ha_pacemaker_cluster_hacluster_user_password",
    "sap_ha_pacemaker_cluster_hacluster_user_password": "PASSWORD"
}
ok: [nw750ahahdb0] => (item=__sap_ha_pacemaker_cluster_hacluster_user_password) => {
    "__sap_ha_pacemaker_cluster_hacluster_user_password": "VARIABLE IS NOT DEFINED!",
    "ansible_loop_var": "item",
    "item": "__sap_ha_pacemaker_cluster_hacluster_user_password"
}

TASK [../community.sap_install/roles/sap_ha_pacemaker_cluster : SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_repos'] ***
ok: [nw750ahahdb0]
ok: [nw750ahahdb1]

TASK [../community.sap_install/roles/sap_ha_pacemaker_cluster : Debug before after change] ***********************************************
ok: [nw750ahahdb0] => (item=ha_cluster_hacluster_password) => {
    "ansible_loop_var": "item",
    "ha_cluster_hacluster_password": "",
    "item": "ha_cluster_hacluster_password"
}
ok: [nw750ahahdb0] => (item=sap_ha_pacemaker_cluster_hacluster_user_password) => {
    "ansible_loop_var": "item",
    "item": "sap_ha_pacemaker_cluster_hacluster_user_password",
    "sap_ha_pacemaker_cluster_hacluster_user_password": "PASSWORD"
}
ok: [nw750ahahdb0] => (item=__sap_ha_pacemaker_cluster_hacluster_user_password) => {
    "__sap_ha_pacemaker_cluster_hacluster_user_password": "",
    "ansible_loop_var": "item",
    "item": "__sap_ha_pacemaker_cluster_hacluster_user_password"
}

```

This results into "__sap_ha_pacemaker_cluster_hacluster_user_password": "" which skips both step 3 and 4 because it is defined already, ignoring user input in sap_ha_pacemaker_cluster_hacluster_user_password

**Pull request merged**
