### PR TITLE
sap_general_preconfigure: Revert to ignoring DNS failures

### PR DESCRIPTION
**Pull request by berndfinger**
Solves issue #784.

### CODE REVIEW

**Review by sean-freeman — APPROVED** [review]
lgtm 👍

**Comment by berndfinger** [comment]
@rhmk Is not available this week, so I removed him from the list of reviewers.
@rob0d Please have a look at this PR and comment.

**Comment by rob0d** [comment]
@berndfinger  yes, it would make it safer and more flexible to make the strict check optional and use something like `sap_general_preconfigure_dns_check_strict: false` as a default.
We can possibly also enhance the PTR check to search through all returned records in a hope that one will match as mentioned in #784 as it will possibly help with the Azure behaviour that @sean-freeman  mentioned. I'm not sure if it's worth the effort though.
I can have a look at this, but I am away until 15th July.

**Comment by berndfinger** [comment]
I'm going to merge this PR now to get back the previous default behavior while also implementing an option to enforce strict DNS checking. We can continue discussing further options in the issue and see if we want or can improve the DNS checking later.

**Pull request merged**
