### PR TITLE
sap_general_preconfigure: cleanup for ansible-lint 6.22.0

### PR DESCRIPTION
**Pull request by berndfinger**
Solves issue #535.

### CODE REVIEW

**Comment by berndfinger** [comment]
I will also cleanup the other two preconfigure roles as part of this PR. So I converted this PR to draft.

**Comment by berndfinger** [comment]
I have trouble with diverged branches for which I do not have time to solve right now, so going back from Draft to standard PR now.

**Review by ja9fuchs — APPROVED** [review]
lgtm

**Review by rainerleber — APPROVED** [review]
lgtm

**Pull request merged**
