### PR TITLE
collection/workflow: Fix workflow issues

### PR DESCRIPTION
**Pull request by berndfinger**
Solves issue #621 (hopefully).

The workflows are now also watching a branch named "github-workflow-test". If such a branch exists, a workflow will be triggered if there is a change to a file of the role in this branch. Can be useful for testing.

See also https://github.com/berndfinger/community.sap_install/actions/runs/7671935703/job/20911364277 .

### CODE REVIEW

**Comment by Wabri** [comment]
I test it again in my fork and it works: https://github.com/Wabri/community.sap_install/actions/runs/7671846479

I saw that I put one job name `ansible-lint` layer too many

**Review by ja9fuchs — APPROVED** [review]
lgtm

**Review by Wabri — CHANGES_REQUESTED** [review]
After some tests, we should remove `github-workflow-test` in the list of branches on line 25 of every single file.

If you want to automatically close the #621 after the merge we should add to the description `Closes #621`

**Review by sean-freeman — APPROVED** [review]
lgtm 👍

**Pull request merged**
