### PR TITLE
collection: Use license_file in galaxy.yml

### PR DESCRIPTION
**Pull request by berndfinger**
Solves issue #617.

### CODE REVIEW

**Comment by berndfinger** [comment]
> LGTM, did you try how it looks in galaxy after build? I am checking some other collections but I dont see galaxy.yml in those.

Yes, the file `galaxy.yml` is used for creating the collection but apparently it's not part of the resulting collection tar file. https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html explains it as follows:
"A key component of an Ansible collection is the galaxy.yml file placed in the root directory of a collection. This file contains the metadata of the collection that is used to generate a collection artifact."

**Review by marcelmamula — APPROVED** [review]
LGTM

**Review by rhmk — APPROVED** [review]
LGTM

**Review by sean-freeman — APPROVED** [review]
lgtm 👍

**Pull request merged**
