### PR TITLE
sap_install_media_detect: Allow detection of SAPEXE only

### PR DESCRIPTION
**Pull request by berndfinger**
Solves issue #729.

### CODE REVIEW

**Comment by berndfinger** [comment]
I successfully tested with S/4HANA 2022 and with `sap_install_media_detect_kernel_db` unset (1) and set to `absent` (2).
When unset (1) , the output showed correct content for the variables `sap_swpm_kernel_dependent_path` and `sap_swpm_kernel_dependent_file_name`. When set to `absent` (2), the two variables were empty.

**Comment by sean-freeman** [comment]
To confirm, this PR is to allow detection of "only SAPEXE" and "only SAPEXEDB" indepedently?

The current AND/OR logic seems to not match the above statement.

**Comment by berndfinger** [comment]
> To confirm, this PR is to allow detection of "only SAPEXE" and "only SAPEXEDB" indepedently?

This PR is meant to support the detection of "only SAPEXE". By setting `sap_install_media_detect_kernel_db` to `none`, the role will no longer look for a SAPEXEDB file and will not report the two related output parameters for SAPEXEDB. If `sap_install_media_detect_kernel` is set to `true` and `sap_install_media_detect_kernel_db` is not set, the behavior is the same as before, meaning that the role will detect SAPEXE and SAPEXEDB.

If `sap_install_media_detect_kernel_db` is set and `sap_install_media_detect_kernel` is not set, the role will not display the output parameters for SAPEXE and SAPEXEDB. Also this case is probably not applicable, and it is out of scope for issue https://github.com/sap-linuxlab/community.sap_install/issues/729.

**Review by sean-freeman — APPROVED** [review]
lgtm 👍

**Pull request merged**
