### PR TITLE
sap_netweaver_preconfigure: Use meta/argument_specs.yml

### PR DESCRIPTION
**Pull request by berndfinger**
At the same time, remove OS dependent vars where possible (`sap_netweaver_preconfigure_min_swap_space_mb` in this case).

Solves issue https://github.com/sap-linuxlab/community.sap_install/issues/321.

The role's file README.md will be updated as the next step.

### CODE REVIEW

**Review by ja9fuchs — APPROVED** [review]
Lgtm

**Comment by rainerleber** [comment]
Lgtm - It seams there is no breaking change. But one thing from in my opinion. If documentation says 'default: true' the value shouldn't yes/no.

The Ansible decision is adapting true/false instead of yes/no

**Comment by berndfinger** [comment]
I agree. The next step is to create a new README.md. And I think we should now switch to `true`/`false` for all the roles in this collection.

**Review by rhmk — APPROVED** [review]
lgtm

**Review by rainerleber — APPROVED** [review]

**Pull request merged**
