### PR TITLE
Few minor fixes and stability fix for current cluster role

### PR DESCRIPTION
**Pull request by rhmk**

### CODE REVIEW

**Comment by berndfinger** [comment]
lgtm.

**Review by berndfinger — APPROVED** [review]

**Comment by sean-freeman** [comment]
Replacement/New Ansible Role `sap_ha_cluster` is WIP, fix for Ansible Role `sap_swpm` already included - therefore closing this PR and will check this fix in the new code.

**Comment by rhmk** [comment]
When will the new cluster role come? D

**Comment by rhmk** [comment]
When will the new cluster role come. Do we want to live with that bug for the next month's

**Comment by rhmk** [comment]
I can wait a week, but not months

**Comment by rhmk** [comment]
didn*'t get, that the new role is renamed

**Pull request closed without merging**
