### PR TITLE
sap_swpm: Add optional flag to prevent redoing ownership change

### PR DESCRIPTION
**Pull request by rnozaki**
This is a suggestion for issue #663

### CODE REVIEW

**Comment by berndfinger** [comment]
@rnozaki Thanks for the PR. I am currently working on a different solution, which would be:
- Change the ownership to `root:root` and permissions **of the directories only**, and of all files with file names starting with **SAPCAR**, to `0755`. Use a role parameter named `sap_swpm_set_directory_sapcar_permissions` to optionally **skip** this step.
- Change the ownership to `root:root` and permissions **of all files only, except SAPCAR** to `0644`. Use a role parameter named `sap_swpm_set_file_permissions` to optionally **skip** this step. If we find out during the testing phase that the permissions of the files have never been wrong, we can skip this step by default and use this role parameter to optionally **enable** this step.

What do you think about this?

**Comment by rnozaki** [comment]
Looks like a viable approach.

We just need to make sure that any ownership change that must be done, be done at least once (initially).

**Comment by berndfinger** [comment]
> We just need to make sure that any ownership change that must be done, be done at least once (initially).

@rnozaki Please have a look at https://github.com/sap-linuxlab/community.sap_install/pull/665 .

**Comment by rnozaki** [comment]
> > We just need to make sure that any ownership change that must be done, be done at least once (initially).
> 
> @rnozaki Please have a look at #665 .

Yes, that looks good, Bernd. That will cover what I requested in issue #663 .

When do you think this will be released?

**Comment by berndfinger** [comment]
> When do you think this will be released?
Now ;-) (as part of dev)

**Pull request closed without merging**
