### PR TITLE
collection: Add collection dependency for community.general

### PR DESCRIPTION
**Pull request by berndfinger**
for fixing the galaxy-importer error "syntax-check[unknown-module]: couldn'\''t resolve module/action '\''community.general.zypper'\''"

### CODE REVIEW

**Review by Wabri — APPROVED** [review]
LGTM

**Review by sean-freeman — APPROVED** [review]
Necessary dependency. I'm not happy about it, but we need to do this for the foreseeable future.

**Comment by berndfinger** [comment]
FYI: This modification caused error messages of type:
```
ERROR    [WARNING]: Collection at '(directory)' does not have a MANIFEST.json file, nor has it galaxy.yml: cannot detect version.
```
and:
```
ERROR! Unexpected Exception, this is probably a bug: Non integer values in LooseVersion ('latest')
```
as the last line, when running `ansible-lint` locally.

I could avoid this error by running:
```
ansible-lint --project-dir .
```
instead.

**Comment by Wabri** [comment]
Why didn't the ci/cd throw this error?

**Comment by berndfinger** [comment]
> Why didn't the ci/cd throw this error?

Good question. Here's another one: Why, even after merging this PR, does the `galaxy-importer` still show the same `syntax-check[unknown-module]: couldn'\''t resolve module/action '\''community.general.zypper'\''` error message? See [here](https://ansible.softwarefactory-project.io/zuul/build/b9fea2771afe49d6b789b423af028b74/log/job-output.txt#666).

**Pull request merged**
