### PR TITLE
sap_*_preconfigure: Tests with ansible parameter -i instead of -l #671

### PR DESCRIPTION
**Pull request by streitd**
This PR is changing ansible-playbook parameter `-l` to `-i` in tests scripts.
No more need to specify hosts in the file `/etc/ansible/hosts` each time.

### CODE REVIEW

**Review by Wabri — APPROVED** [review]

**Comment by berndfinger** [comment]
Hi @streitd,
We should also add `-u root` to the `ansible-playbook` command (so that a normal user can also run the test).
We also should fix the same issue for the role `sap_hana_install` .
Feel free to use the code from https://github.com/berndfinger/community.sap_install/commit/8c40e91ec3d881533d25843efd1af16448a8ba16 and add it as a new commit to your branch so that it will be part of this PR.

**Review by berndfinger — APPROVED** [review]
LGTM!

**Review by berndfinger — CHANGES_REQUESTED** [review]
Wait! We need to merge into dev, not in main.

**Review by berndfinger — CHANGES_REQUESTED** [review]
I tried to modify the destination branch to `main` but this would lead to lots of other changes to be reverted.
@streitd Can you please create a new PR with all the changes but based on the upstream dev tree?

**Pull request closed without merging**
