### PR TITLE
sap_anydb_install_oracle: fix hardcoded oraInventory path and replace export with setenv

### PR DESCRIPTION
**Pull request by rnozaki**
Addresses issues:
#587 
#588

### CODE REVIEW

**Comment by rnozaki** [comment]
@sean-freeman : this is a simple fix... could it be checked and included in the next update?

**Comment by rnozaki** [comment]
@berndfinger: this is a simple fix... could it be checked and included in the next update?

**Comment by sean-freeman** [comment]
Will be included in 1.4.0, the imminent next release

**Review by sean-freeman — APPROVED** [review]
lgtm 👍

**Pull request merged**
