### PR TITLE
sap_install_media_detect: S4HANA Java stack installation

### PR DESCRIPTION
**Pull request by remrozk**
### Context
SAP S/4HANA Java stack is still using SWPM1 (https://help.sap.com/doc/6b11678926d3409bbfea8897cb34d10f/2023/en-US/INST_OP2023.pdf) and still needs DATA_UNITS to be installed.
s4hana_java

### Enhancement

- Create new value `saps4hana_java` for the var `sap_install_media_detect_export`
- Update sapfile to be able to detect `sap_export_s4hana_java`
- Update `roles/sap_install_media_detect/tasks/find_files_after_extraction.yml` in order to manage `sap_export_s4hana_java`
- Update `roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml` in order to manage `sap_export_s4hana_java`
- Update `roles/sap_install_media_detect/tasks/set_global_vars.yml` in order to manage `saps4hana_java`

### Output
```log
TASK [community.sap_install.sap_install_media_detect : SAP Install Media Detect - Prepare - Set fact with the results of the sapfile command]
...
ok: [sj4hwpas] => (item={'changed': False, 'stdout': '/tmp/sap_media_installation/51057035.ZIP;sap_export_s4hana_java;sap_export_s4hana_java;sap_export_s4hana_java_extracted;zip;y;n', 'stderr': '', 'rc': 0, 'cmd': ['/tmp/ansible.wd5gago1media_detect/sapfile', '-e', '--lsar_file=/usr/bin/unrar', '--sapcar_file=/tmp/sap_media_installation/SAPCAR_1200-70007716.EXE', '/tmp/sap_media_installation/51057035.ZIP'], 'start': '2024-04-08 15:51:31.069897', 'end': '2024-04-08 15:51:31.085330', 'delta': '0:00:00.015433', 'msg': '', 'invocation': {'module_args': {'_raw_params': '/tmp/ansible.wd5gago1media_detect/sapfile -e --lsar_file=/usr/bin/unrar --sapcar_file=/tmp/sap_media_installation/SAPCAR_1200-70007716.EXE /tmp/sap_media_installation/51057035.ZIP', '_uses_shell': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}, 'stdout_lines': ['/tmp/sap_media_installation/51057035.ZIP;sap_export_s4hana_java;sap_export_s4hana_java;sap_export_s4hana_java_extracted;zip;y;n'], 'stderr_lines': [], 'failed': False, 'line_item': '/tmp/sap_media_installation/51057035.ZIP', 'ansible_loop_var': 'line_item'})
...

...

TASK [community.sap_install.sap_install_media_detect : SAP Install Media Detect - Detection completed - Display result]
ok: [sj4hwpas] => {
    "msg": [
        ...
        "sap_swpm_cd_export_path = >/tmp/sap_media_installation/sap_export_s4hana_java_extracted/51057035/DATA_UNITS/
        ...
    ]
}

...

TASK [community.sap_install.sap_swpm : SAP SWPM Deployment - Finished]
ok: [sj4hwpas] => {
    "msg": [
        "   SAP SWPM deployment successfully completed ",
        " ",
        "   SAP Product        -       NW_Java_OneHost:S4HANA2023.JAVA.HDB.PD  ",
        "   SID                -       S4J ",
        "   Primary Instance   -       01 ",
        "   Host               -       sj4hwpas ",
        "   FQDN               -       sj4hwpas.mydomain.local  ",
        "   IP                 -       X.X.X.X  "
    ]
}
```

### CODE REVIEW

**Comment by sean-freeman** [comment]
Will need to test, I think SAP S/4HANA JAVA can be detected using the existing `sap_export_nwas_java` logic.

Files in S/4HANA JAVA download
```shell
[:51057035] $ tree -L 3
.
├── CDLABEL.ASC
├── CDLABEL.EBC
├── COPY_TM.HTM
├── COPY_TM.TXT
├── DATA_UNITS
│   ├── LABELIDX.ASC
│   ├── ADVANCED_ADAPTER_ENGINE_EXTND
│   │   ├── GWJPO28_0.SCA
│   │   ├── INTGVIS28_0.SCA
│   │   ├── INTGVISDCJ28_0.SCA
│   │   ├── LABEL.ASC
│   │   ├── PISCPBUILDT28_0.SCA
│   │   ├── PISCPEXT28_0.SCA
│   │   ├── SAPXIADMIN28_0.SCA
│   │   ├── SAPXIAF28_0.SCA
│   │   ├── SAPXIAFCON28_0.SCA
│   │   ├── SAPXIIGWAPPL28_0.SCA
│   │   ├── SAPXIIGWCORE28_0.SCA
│   │   ├── SAPXIPIT28_0.SCA
│   │   ├── SAPXIPITCORE28_0.SCA
│   │   ├── SAPXITOOL28_0.SCA
│   │   ├── SIGNATURE.SMF
│   │   └── SOAMON28_0.SCA
│   ├── EHS_EXPERT_SERVER
│   │   ├── EHSEXP32_59.EXE
│   │   ├── LABEL.ASC
│   │   └── SIGNATURE.SMF
│   ├── EHS_WWI_SERVER
│   │   ├── EHSWWI32_59.EXE
│   │   ├── LABEL.ASC
│   │   └── SIGNATURE.SMF
│   ├── ESR_CONTENT
│   │   ├── CNTLOC60509_2.ZIP
│   │   ├── LABEL.ASC
│   │   ├── MDGAPPL808_0.ZIP
│   │   ├── MDGFND808_0.ZIP
│   │   ├── SIGNATURE.SMF
│   │   ├── SWIFT62200_4.ZIP
│   │   ├── XICNTEADFPS00_0.ZIP
│   │   ├── XICNTEAPS00_0.ZIP
│   │   ├── XICNTELSTER00_0.ZIP
│   │   ├── XICNTISOIL00_0.ZIP
│   │   ├── XICNTISPRA00_0.ZIP
│   │   ├── XICNTISPSCA00_0.ZIP
│   │   ├── XICNTISUT00_0.ZIP
│   │   ├── XICNTS4CEXT00_0.ZIP
│   │   ├── XICNTS4CORE00_0.ZIP
│   │   ├── XICNTS4COREOP00_0.ZIP
│   │   ├── XICNTS4DEPREC00_0.ZIP
│   │   ├── XICNTS4FND00_0.ZIP
│   │   └── XICNTSAPS4HCM00_0.ZIP
│   ├── HANA
│   │   ├── HANAUMML12_6.ZIP
│   │   ├── HCORULEFW11_10.ZIP
│   │   ├── LABEL.ASC
│   │   ├── LINPPC64LE
│   │   ├── LINUX_X64
│   │   ├── NT_X64
│   │   └── SIGNATURE.SMF
│   ├── JAVA_EXPORT
│   │   ├── DB
│   │   ├── LABEL.ASC
│   │   └── SIGNATURE.SMF
│   ├── JAVA_EXPORT_JDMP
│   │   ├── EXPDUMP.001
│   │   ├── IMPORT.XML
│   │   ├── LABEL.ASC
│   │   ├── SIGNATURE.SMF
│   │   └── TOC.XML
│   ├── JAVA_J2EE_OSINDEP
│   │   ├── JDKVersion.xml
│   │   ├── KernelVersions.xml
│   │   ├── LABEL.ASC
│   │   ├── SIGNATURE.SMF
│   │   └── TOC.XML
│   ├── JAVA_J2EE_OSINDEP_J2EE_INST
│   │   ├── J2EEINSTALL.SDA
│   │   ├── J2EESTARTUP.SDA
│   │   ├── LABEL.ASC
│   │   ├── SAP.COM~SYNCLOG.SDA
│   │   ├── SIGNATURE.SMF
│   │   └── TOC.XML
│   ├── JAVA_J2EE_OSINDEP_UT
│   │   ├── ADSSAP28_1.SCA
│   │   ├── AJAXRUNTIME28_1.SCA
│   │   ├── BASETABLES28_0.SCA
│   │   ├── BIUDI28_0.SCA
│   │   ├── BIWDALV28_0.SCA
│   │   ├── CFGZA28_0.SCA
│   │   ├── CFGZACE28_0.SCA
│   │   ├── COMPBUILDT28_0.SCA
│   │   ├── CORETOOLS28_1.SCA
│   │   ├── CUBASEJAVA28_0.SCA
│   │   ├── CUBASEWD28_0.SCA
│   │   ├── DATAMAPPING28_0.SCA
│   │   ├── DICLIENTS28_0.SCA
│   │   ├── ECMCORE28_0.SCA
│   │   ├── ENGFACADE28_0.SCA
│   │   ├── ENGINEAPI28_0.SCA
│   │   ├── EPBASIS28_0.SCA
│   │   ├── EPBASISAPI28_0.SCA
│   │   ├── ESCONFBUILDT28_0.SCA
│   │   ├── ESIUI28_0.SCA
│   │   ├── ESMPBUILDT28_0.SCA
│   │   ├── ESPFRAMEWORK28_0.SCA
│   │   ├── ESREGBASIC28_0.SCA
│   │   ├── ESREGSERVICES28_0.SCA
│   │   ├── FRAMEWORK28_0.SCA
│   │   ├── FRAMEWORKEXT28_0.SCA
│   │   ├── GWJPO28_0.SCA
│   │   ├── INTGVIS28_0.SCA
│   │   ├── INTGVISDCJ28_0.SCA
│   │   ├── J2EEAPPS28_0.SCA
│   │   ├── J2EEFRMW28_0.SCA
│   │   ├── JSPM28_0.SCA
│   │   ├── KMKWJIKS28_0.SCA
│   │   ├── LABEL.ASC
│   │   ├── LMCFG28_0.SCA
│   │   ├── LMCORE28_0.SCA
│   │   ├── LMCTC28_0.SCA
│   │   ├── LMCTS28_0.SCA
│   │   ├── LMCTSUI28_0.SCA
│   │   ├── LMMODELBASE28_0.SCA
│   │   ├── LMMODELNW28_0.SCA
│   │   ├── LMNWABASICAPPS28_0.SCA
│   │   ├── LMNWABASICCOMP28_0.SCA
│   │   ├── LMNWABASICMBEAN28_0.SCA
│   │   ├── LMNWACDP28_0.SCA
│   │   ├── LMNWATOOLS28_0.SCA
│   │   ├── LMNWAUIFRMRK28_0.SCA
│   │   ├── LMSLD28_0.SCA
│   │   ├── LMTOOLS28_0.SCA
│   │   ├── MESSAGING28_0.SCA
│   │   ├── MMRSERVER28_0.SCA
│   │   ├── MOINBUILDT28_0.SCA
│   │   ├── NWTEC28_0.SCA
│   │   ├── ODATACXFEXT28_0.SCA
│   │   ├── PISCPBUILDT28_0.SCA
│   │   ├── PISCPEXT28_0.SCA
│   │   ├── SAPBUILDT28_0.SCA
│   │   ├── SAPXI3RDPARTY28_0.SCA
│   │   ├── SAPXIADMIN28_0.SCA
│   │   ├── SAPXIAF28_0.SCA
│   │   ├── SAPXIAFCON28_0.SCA
│   │   ├── SAPXIESR28_0.SCA
│   │   ├── SAPXIGUILIB28_0.SCA
│   │   ├── SAPXIIGWAPPL28_0.SCA
│   │   ├── SAPXIIGWCORE28_0.SCA
│   │   ├── SAPXIPIT28_0.SCA
│   │   ├── SAPXIPITCORE28_0.SCA
│   │   ├── SAPXITOOL28_0.SCA
│   │   ├── SECURITYEXT28_0.SCA
│   │   ├── SERVERCORE28_0.SCA
│   │   ├── SERVICECOMP28_0.SCA
│   │   ├── SIGNATURE.SMF
│   │   ├── SOAMON28_1.SCA
│   │   ├── SOAMONBASIC28_0.SCA
│   │   ├── SRUI28_0.SCA
│   │   ├── SUPPORTTOOLS28_0.SCA
│   │   ├── SWLIFECYCL28_0.SCA
│   │   ├── TOC.XML
│   │   ├── UDDI28_0.SCA
│   │   ├── UISAPUI5JAVA28_0.SCA
│   │   ├── UKMSJAVA28_0.SCA
│   │   ├── UMEADMIN28_0.SCA
│   │   ├── WDADOBE28_0.SCA
│   │   ├── WDAPPS28_0.SCA
│   │   ├── WDRUNTIME28_0.SCA
│   │   ├── WDRUNTIMEEXT28_0.SCA
│   │   ├── WSRM28_0.SCA
│   │   ├── XICNTSAPBASIS28_0.SCA
│   │   └── pv_descriptor.xml
│   └── S4_JAVA
│       ├── AIX_64
│       ├── ELSTER00_6.SCA
│       ├── LABEL.ASC
│       ├── LINUX_X64
│       ├── NT_X64
│       ├── SIGNATURE.SMF
│       ├── SWIFT01_23.SCA
│       ├── UTELSTER00_2.SCA
│       └── UTSWIFT00_1.SCA
├── LABEL.ASC
├── LABEL.EBC
├── LABELIDX.ASC
├── MD5FILE.DAT
├── MID.XML
├── SHAFILE.DAT
├── VERSION.ASC
└── VERSION.EBC
```

**Comment by sean-freeman** [comment]
Confirmed, script file within Ansible Role incorrectly detects

```shell
/sapfile -e --lsar_file=/usr/bin/lsar --sapcar_file=/software/SAPCAR_1115-70006178.EXE /software/51057035.zip

/software/51057035.zip;sap_export_ecc_ides;sap_export_ecc_ides;sap_export_ecc_ides_extracted;zip;y;n
```

**Comment by berndfinger** [comment]
@remrozk Many thanks for reporting this. It appears to be a new file type, which indeed needs an update in `sap_install_media_detect`. The yml code change you proposed seems to be correct.
The code change you proposed for the sapfile tool appears to work (as you showed in the output) but the risk is that depending on the order of the files inside the zip file, the file type might still be detected incorrectly because there is more than one match with the awk search strings.
My proposal in https://github.com/sap-linuxlab/community.sap_install/compare/dev...berndfinger:community.sap_install:issue-699?expand=1 solves this problem by exiting after the first match.

Regarding this PR, it has unfortunately opened against the `main` tree so we cannot merge it. We also cannot merge it into the `dev` tree because it would cause previous code in other places to be overwritten (I found out after changing the destination branch).

So my proposal is now:
- You close this PR.
- We test the modifications to the `sapfile` command, for which I will open a new PR once we have finished some initial testing.
- You then open the PR with your changes again but only after pulling the latest changes of the `dev` tree into your fork, and by opening it against the `dev` tree.

**Comment by remrozk** [comment]
Hello @berndfinger,

Thank you to take in consideration my PR. So as asked, I close this PR and I'm waiting the new version of sapfile before creating the same PR (from dev tree).

**Comment by berndfinger** [comment]
Hi @remrozk - As per https://github.com/sap-linuxlab/community.sap_install/pull/701#issuecomment-2052088652 by @sean-freeman , the sap_swpm role also works if the file type of `51057035.ZIP` is detected as `sap_export_nwas_java`.
I will now merge https://github.com/sap-linuxlab/community.sap_install/pull/701. Could you please re-test and report if the problem is solved with this change?

**Comment by remrozk** [comment]
Hello @berndfinger,

With #701, the value `sapnwas_java` works fine for S/4HANA Java, thanks!

```
ok: [sj4hpas] => (item={'changed': False, 'stdout': '/tmp/sap_media_installation/51057035.ZIP;sap_export_nwas_java;sap_export_nwas_java;sap_export_nwas_java_extracted;zip;y;n', 'stderr': '', 'rc': 0, 'cmd': ['/tmp/ansible.0ph6f3x2media_detect/sapfile', '-e', '--lsar_file=/usr/bin/unrar', '--sapcar_file=/tmp/sap_media_installation/SAPCAR_1200-70007716.EXE', '/tmp/sap_media_installation/51057035.ZIP'], 'start': '2024-04-16 10:35:46.808183', 'end': '2024-04-16 10:35:46.833431', 'delta': '0:00:00.025248', 'msg': '', 'invocation': {'module_args': {'_raw_params': '/tmp/ansible.0ph6f3x2media_detect/sapfile -e --lsar_file=/usr/bin/unrar --sapcar_file=/tmp/sap_media_installation/SAPCAR_1200-70007716.EXE /tmp/sap_media_installation/51057035.ZIP', '_uses_shell': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}, 'stdout_lines': ['/tmp/sap_media_installation/51057035.ZIP;sap_export_nwas_java;sap_export_nwas_java;sap_export_nwas_java_extracted;zip;y;n'], 'stderr_lines': [], 'ansible_facts': {'discovered_interpreter_python': '/usr/bin/python3.6'}, 'failed': False, 'line_item': '/tmp/sap_media_installation/51057035.ZIP', 'ansible_loop_var': 'line_item'})
```

```
TASK [community.sap_install.sap_install_media_detect : SAP Install Media Detect - Detection completed - Display result] **********************************************************************************************************************
ok: [sj4hpas] => {
    "msg": [
        "sap_hana_install_directory = >/tmp/sap_media_installation/sap_hana/<",
        "sap_hana_install_software_directory = >/tmp/sap_media_installation/sap_hana/<",
        "sap_hana_install_software_extract_directory = >/tmp/sap_media_installation/sap_hana_extracted/<",
        "sap_anydb_install_oracle_extract_path = ><",
        "sap_swpm_swpm_path = >/tmp/sap_media_installation/sap_swpm/<",
        "sap_swpm_software_path = >/tmp/sap_media_installation/sap_swpm_download_basket<",
        "sap_swpm_cd_ibmdb2_path = ><",
        "sap_swpm_cd_oracle_path = ><",
        "sap_swpm_cd_sapase_path = ><",
        "sap_swpm_cd_sapmaxdb_path = ><",
        "sap_swpm_cd_rdbms_path = >/tmp/sap_media_installation/sap_hana_client_extracted/SAP_HANA_CLIENT/<",
        "sap_swpm_cd_ibmdb2_client_path = ><",
        "sap_swpm_cd_oracle_client_path = ><",
        "sap_swpm_cd_sapase_client_path = ><",
        "sap_swpm_cd_export_path = >/tmp/sap_media_installation/sap_export_nwas_java_extracted/51057035/DATA_UNITS/<",
        "sap_swpm_cd_export_pt1_path = ><",
        "sap_swpm_cd_export_pt2_path = ><",
        "sap_swpm_sapcar_path = >/tmp/sap_media_installation/<",
        "sap_swpm_sapcar_file_name = >SAPCAR_1200-70007716.EXE<",
        "sap_swpm_igs_path = >/tmp/sap_media_installation/sap_swpm_download_basket/<",
        "sap_swpm_igs_file_name = >igsexe_4-80007786.sar<",
        "sap_swpm_igs_helper_path = >/tmp/sap_media_installation/sap_swpm_download_basket/<",
        "sap_swpm_igs_helper_file_name = >igshelper_17-10010245.sar<",
        "sap_swpm_kernel_dependent_path = >/tmp/sap_media_installation/sap_swpm_download_basket/<",
        "sap_swpm_kernel_dependent_file_name = >SAPEXEDB_300-80007611.SAR<",
        "sap_swpm_kernel_independent_path = >/tmp/sap_media_installation/sap_swpm_download_basket/<",
        "sap_swpm_kernel_independent_file_name = >SAPEXE_300-80007612.SAR<",
        "sap_swpm_web_dispatcher_path = ><",
        "sap_swpm_web_dispatcher_file_name = ><",
        "sap_swpm_mp_stack_path = ><",
        "sap_swpm_mp_stack_file_name = ><"
    ]
}
```
```
TASK [community.sap_install.sap_swpm : SAP SWPM Deployment - Finished] ***********************************************************************************************************************************************************************
ok: [sj4hpas] => {
    "msg": [
        "   SAP SWPM deployment successfully completed ",
        " ",
        "   SAP Product        -       NW_Java_OneHost:S4HANA2023.JAVA.HDB.PD  ",
        "   SID                -       S4J ",
        "   Primary Instance   -       01 ",
        "   Host               -       sj4hpas ",
        "   FQDN               -       sj4hpas.mydomain.local  ",
        "   IP                 -       XXX.XXX.XXX.XXX  "
    ]
}
```

**Comment by sean-freeman** [comment]
@remrozk see also #707 to ease S/4HANA Java installations, which will also be added to [ansible.playbooks_for_sap](https://github.com/sap-linuxlab/ansible.playbooks_for_sap) in the next release

**Comment by remrozk** [comment]
Thanks @sean-freeman

**Pull request closed without merging**
