### PR TITLE
sap_anydb_install_oracle: Add code for Oracle patches

### PR DESCRIPTION
**Pull request by rnozaki**
Addresses issue #612

### CODE REVIEW

**Comment by rnozaki** [comment]
@berndfinger , @sean-freeman : I added this code and validated in my customer... could it be checked and included in the next update?

**Review by sean-freeman — APPROVED** [review]
lgtm 👍

**Comment by sean-freeman** [comment]
@rnozaki no further changes? From the look, the patch functionality looks complete

**Comment by rnozaki** [comment]
No further changes... When is this expected to be released?

**Pull request merged**
