### PR TITLE
sap_swpm: hdbuserstore default connection should use sap_swpm_db_schema_abap_password

### PR DESCRIPTION
**Pull request by rob0d**
issue #747

### CODE REVIEW

**Review by berndfinger — APPROVED** [review]
LGTM

**Comment by sean-freeman** [comment]
Requires regression test

**Comment by rob0d** [comment]
@sean-freeman  I tested this on two S/4 installations. Third one will be done this week.
Is this enough or do you want to do your separate regression test?

**Comment by berndfinger** [comment]
@rob0d I also just tested this code and the S/4HANA installation went through, as expected. Can you think of, or do you know, an easy way to verify the success? For example, by running `hdbuserstore` with certain options?

**Comment by sean-freeman** [comment]
We should probably add a comment that indicates the `@{{ sap_swpm_db_sid }}` means this code is only applicable for SAP HANA MDC architecture setup (which is defacto), which should perhaps be a restriction for the `sap_swpm` Ansible Role?

I do not want to slow this PR down any further, as I am very confident @rob0d is correct - running a regression test was for my own sanity. I will test the `dev` branch in the near future, which will test this PR too.

----

@berndfinger To answer your validation question, quickly formulated the following from my own debugging notes - it might be useful and @rob0d should confirm

At end of sap_hana_install, could login to <sap_hana_install_sid>adm and run....
```shell
/usr/sap/{{ sap_hana_install_sid | upper }}/HDB{{ sap_hana_install_number }}/exe/hdbsql \
-i {{ sap_hana_install_number }} \
-d SYSTEMDB \ # line added for database name, aka MDC Tenant 'SYSTEMDB'
-u SYSTEM \
-p {{ sap_hana_install_db_system_password | d(sap_hana_install_master_password) }} \
-m <<EOF
SELECT * from M_DATABASES;
EOF
```

The MDC Tenant would not have yet been created by SAP SWPM, so you could not run....
```shell
/usr/sap/{{ sap_hana_install_sid | upper }}/HDB{{ sap_hana_install_number }}/exe/hdbsql \
-i {{ sap_hana_install_number }} \
-d {{ sap_hana_install_sid }} \ # line added for database name, aka MDC Tenant Name
-u SYSTEM \
-p {{ sap_hana_install_db_system_password | d(sap_hana_install_master_password) }} \
-m <<EOF
SELECT * from M_DATABASES;
EOF
```

Could perhaps login to <sap_swpm_sid<adm and test connection...

```shell
# SAP Transport binary to test connection to Database
R3trans -d

# ODBC Driver test should not contain "outString(0)L <no out string received from driver>"
# ODBC Driver test should not state "message(....): .... General error;10 authentication failed"
/usr/sap/{{ sap_swpm_sid | upper }}/hdbclient/odbcreg \
{{ sap_swpm_db_host }}:3{{ sap_swpm_db_instance_nr }}13 \
SYSTEMDB \
SYSTEM '{{ sap_swpm_db_systemdb_password }}'

/usr/sap/{{ sap_swpm_sid | upper }}/hdbclient/odbcreg \
{{ sap_swpm_db_host }}:3{{ sap_swpm_db_instance_nr }}15 \
{{ sap_swpm_db_sid }} \
{{ sap_swpm_db_schema_abap }} '{{ sap_swpm_db_schema_abap_password }}'
```

**Review by sean-freeman — APPROVED** [review]

**Comment by berndfinger** [comment]
I am going to merge this PR despite the alternative approach in https://github.com/sap-linuxlab/community.sap_install/pull/802, and continue the discussion there.

**Pull request merged**
