### PR TITLE
collection: Fix ansible-test sanity errors

### PR DESCRIPTION
**Pull request by berndfinger**
Solves issue #646.

### CODE REVIEW

**Comment by berndfinger** [comment]
See also https://github.com/sap-linuxlab/community.sap_install/issues/648 .

**Comment by berndfinger** [comment]
Testing the production relevant changes to the Bash script shebang (from `#!/bin/bash `to `#!/usr/bin/env bash`):
- `tools/beautify-assert-output.sh`: PASS
- `sap_install_media_detect/files/tmp/sapfile`: PASS
- `sap_hana_install/files/tmp/tail-f-hdblcm-install-trc.sh`: PASS

**Review by ja9fuchs — APPROVED** [review]
lgtm

**Review by sean-freeman — APPROVED** [review]
lgtm 👍

**Comment by berndfinger** [comment]
@Wabri Could you please approve this PR?

**Review by Wabri — COMMENTED** [review]
The shebang with `env` is a good practice so LGTM 💯 

You refer this PR also to #648 , but there are no resolution about that in this PR, am I right?

**Comment by Wabri** [comment]
If you want to close the issue #646 automatically after the merge you can put: Closes #646 on the description!

**Comment by berndfinger** [comment]
> If you want to close the issue #646 automatically after the merge you can put: Closes #646 on the description!
Thanks, I also thought about it but for the time being I want to close the issue(s) manually.

**Pull request merged**
